# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f79b1473a413428a22899b3b25b5d54c94dc89ed7b7107ca1d7c1c096d40f38e4967d0ea91bc49849e2e7e4682ff4482802ffb8fdb4dbb3a7c2355303853087c

test:
  secret_key_base: a674ef8d11bec0eef84b10c7eb31fba37ae6d4ebfba8d97249c185ebdae277bf50ec026f58065bfdd736e86732853a13c5f0c8956f2d5611eb7a2cb434568376

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
